version: '3.3'

x-logging: &x-logging
  logging:
    driver: "json-file"
    options:
      max-size: "100m"
      max-file: "10"
      tag: "{{.ImageName}}|{{.Name}}"

services:
  timeweb:
    image: passkeyra/timeweb:latest
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 100M
    <<: *x-logging

  nginx:
    build: ./nginx
    image: nginx.timeweb
    ports:
      - "80:80"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 100M
    <<: *x-logging

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - ./grafana/config.monitoring
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 100M
    <<: *x-logging

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 100M
    <<: *x-logging


  promtail:
    image: grafana/promtail
    expose:
      - 9080
    ports:
      - "9080:9080"
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - promtail_data:/var/lib/promtail/positions
      - ./promtail/promtail.yml:/etc/promtail/promtail.yml
    command:
      - '-config.file=/etc/promtail/promtail.yml'
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 100M
    <<: *x-logging

  loki:
    image: grafana/loki
    expose:
      - 3100
    ports:
      - "3100:3100"
    volumes:
      - ./loki/loki-config.yml:/etc/loki-config.yml
      - loki_data:/loki
    command: -config.file=/etc/loki-config.yml
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 100M
    <<: *x-logging

volumes:
  grafana_data: {}
  loki_data: {}
  promtail_data: {}
  prometheus_data: {}
