---
- name: Install pip
  apt:
    name: python3-pip
    update_cache: true
    state: present
- name: Install docker-compose
  pip:
    name: docker-compose
- name: Start the timeweb container
  become: yes
  docker_container:
    image: "{{ image_name }}"
    name: "{{ container_name  }}"
    ports: '{{ container_ports }}'
    state: 'started'
